---
title: 値を返さないObservableとEventEmitter考察
description: null
tags: angular,rxjs
updatedAt: 2021-11-22
published: true
---

## Subject

https://codesandbox.io/s/sad-meninsky-d3n6j?file=/src/app/app.component.ts:0-43

任意のタイミングで値を流すhotなObservable。
completeするとそれ以上値は流れない。

```ts
const subject = new Subject<number>();

subject.subscribe((v) => {
  console.log(v);
});

// 1が流れる
subject.next(1);

// 2が流れる
subject.next(2);

// 終了
subject.complete();

// 流れない
subject.next(3);
}
```

## EventEmitter

https://github.com/angular/angular/blob/62146365804ba4f50fb87f3173792d7a1dd3f97f/packages/core/src/event_emitter.ts#L105

Subjectをextendsしたクラス。
なのでSubjectと同じ動きをする


## コンポーネントが破棄される時に購読していたObsevableはどうなる？

hotなObservableであれば、延々と購読し続ける。
https://codesandbox.io/s/kind-proskuriakova-6gy4s

```ts
export class FooComponent implements OnInit, OnDestroy {
  observable: Observable<number>;
  count = 0;

  ngOnInit() {
    // FooComponentが破棄された後も延々とconsole出力される。
    this.observable = interval(2000);

    this.observable.subscribe((v) => {
      this.count++;
      console.log("subscribe", this.count);
    });
  }
}
```

## @Outputに値を流し続けたら延々と購読し続ける？

そんな事はない。止まる。
https://codesandbox.io/s/fervent-tess-dzeh2

```ts
// 利用者側はコンポーネントが破棄されると同時にsubscribeしなくなる
@Component({
  template: `<counter (next)="next()">`
})
export class FooComponent {
  next(v) {
    console.log("subscribe", v);
  }
}

// Observable発生元コンポーネントはコンポーネント自体が破棄されても延々とemitし続ける
export class CounterComponent implements OnInit, OnDestroy {
  @Output() next = new EventEmitter<number>();
  count = 0;

  ngOnInit() {
    setInterval(() => {
      this.count++;
      this.next.emit(this.count);
    }, 2000);
  }
}
```

## subscribe/add/finalizeのタイミング

https://codesandbox.io/s/blissful-sammet-8ug1g

subscribe > add > finalizeの順に呼ばれる。
subscribeまでにn秒かかる時 `(n秒) > subscribe > add > finallize` となる。


```ts
import { timer } from "rxjs";
import { finalize } from "rxjs/operators";

// (1)即時
console.log("exec");

timer(2000)
  .pipe(
    // (4)n秒後
    finalize(() => {
      console.log("finalize");
    })
  )
  // (2)n秒後
  .subscribe(() => {
    console.log("subscribe");
  })
  // (3)n秒後
  .add(() => {
    console.log("add");
  });
```

## 例外をフックしてObservableを返す

https://codesandbox.io/s/holy-dew-wl717

```ts
export class AppComponent {
  click() {
    // completeしか呼ばれない
    this.exec().subscribe(
      () => console.log("next"),
      (e) => console.log("error", e),
      () => console.log("complete")
    );
  }

  exec() {
    console.log("exec()");
    return this.createAsyncTask().pipe(
      // エラーの有無によってアラート出力を分岐する
      tap({
        complete: () => {
          console.log("xxxに成功しました");
        },
        error: () => {
          console.log("xxxに失敗しました");
        }
      }),
      // 完了だけ通知したいのでエラーはなかった事にする
      catchError(() => EMPTY)
    );
  }

  createAsyncTask() {
    // 何らかの非同期タスクのシミュレーション
    console.log("createAsyncTask()");
    return new Observable((observer) => {
      setTimeout(() => {
        // observer.next(111);
        observer.error("hogehogehoge");
        observer.complete();
      }, 2000);
    });
  }
}
```

## EMPTY/NEVER

https://codesandbox.io/s/ecstatic-http-w3kim

### EMPTY

完了通知だけのObservable。
https://rxjs.dev/api/index/const/EMPTY

```ts
// completeが呼ばれる
EMPTY.subscribe({
  next: (v) => console.log("next", v),
  error: (e) => console.log("error", e),
  complete: () => console.log("complete")
});
```

### NEVER

何も放出しないObservable。
https://rxjs.dev/api/index/const/NEVER

```ts
// 何も呼ばれない、subscribeできるだけ
NEVER.subscribe({
  next: (v) => console.log("next", v),
  error: (e) => console.log("error", e),
  complete: () => console.log("complete")
});
```
